import { ROLES } from '../config/roles.js';

// These are development accounts only. Set SEED_USER_PASSWORD before seeding
// any shared environment.
const sampleUsers = [
    {
        fullName: 'Aarav Sharma',
        email: 'student@edupath.local',
        role: ROLES.STUDENT,
        phoneNumber: '+977-9800000001',
        emailVerified: true,
        studentProfile: {
            educationLevel: 'Undergraduate',
            currentCourse: 'BCA',
            preferredCourses: ['BCA', 'BIT', 'BSc CSIT'],
            preferredCities: ['Kathmandu', 'Lalitpur'],
            skills: ['Python', 'Django', 'React'],
            careerInterests: ['Software Development', 'Web Development'],
            preferredOpportunityType: 'internship',
            portfolioLinks: ['https://github.com/aarav-sharma'],
            bio: 'BCA student looking for practical software development opportunities.',
            address: 'Kathmandu, Nepal',
        },
    },
    {
        fullName: 'Nisha Koirala',
        email: 'admin@edupath.local',
        role: ROLES.ADMIN,
        phoneNumber: '+977-9800000002',
        emailVerified: true,
    },
    {
        fullName: 'Ramesh Adhikari',
        email: 'college-admin@edupath.local',
        role: ROLES.COLLEGE_ADMIN,
        phoneNumber: '+977-9800000003',
        emailVerified: true,
    },
    {
        fullName: 'Maya Thapa',
        email: 'employer@edupath.local',
        role: ROLES.EMPLOYER,
        phoneNumber: '+977-9800000004',
        emailVerified: true,
    },
    {
        fullName: 'Sanjay Shrestha',
        email: 'instructor@edupath.local',
        role: ROLES.INSTRUCTOR,
        phoneNumber: '+977-9800000005',
        emailVerified: true,
    },
];

// The first entry in each collection preserves the catalog examples currently
// shown on the home page. `ownerEmail` is resolved to a User by the seed script.
const colleges = [
    {
        identity: { collegeName: 'Kathmandu Tech College', city: 'Kathmandu' },
        ownerEmail: 'college-admin@edupath.local',
        collegeName: 'Kathmandu Tech College',
        city: 'Kathmandu',
        address: 'New Baneshwor, Kathmandu, Nepal',
        affiliation: 'Tribhuvan University',
        courses: ['BCA', 'BIT', 'BSc CSIT'],
        feeRange: 'NPR 250,000 - 420,000 per program',
        facilities: ['Computer labs', 'Library', 'Scholarships', 'Career counseling'],
        rating: 4.6,
        admissionStatus: 'open',
        description: 'Technology-focused undergraduate programs with practical projects and career guidance.',
        contactEmail: 'admissions@kathmandutechcollege.edu.np',
        contactPhone: '+977-1-5970001',
        website: 'https://kathmandutechcollege.edu.np',
        approvalStatus: 'approved',
    },
    {
        identity: { collegeName: 'Lalitpur Business School', city: 'Lalitpur' },
        ownerEmail: 'college-admin@edupath.local',
        collegeName: 'Lalitpur Business School',
        city: 'Lalitpur',
        address: 'Jawalakhel, Lalitpur, Nepal',
        affiliation: 'Tribhuvan University',
        courses: ['BBA', 'BBM', 'BCA'],
        feeRange: 'NPR 300,000 - 480,000 per program',
        facilities: ['Business incubator', 'Library', 'Internship support'],
        rating: 4.3,
        admissionStatus: 'open',
        description: 'Business and technology programs built around applied learning and industry exposure.',
        contactEmail: 'admissions@lalitpurbusiness.edu.np',
        contactPhone: '+977-1-5970002',
        website: 'https://lalitpurbusiness.edu.np',
        approvalStatus: 'approved',
    },
];

const opportunities = [
    {
        identity: { title: 'Python Django Intern', companyName: 'Pi Innovations' },
        employerEmail: 'employer@edupath.local',
        title: 'Python Django Intern',
        companyName: 'Pi Innovations',
        type: 'internship',
        location: 'Kathmandu',
        workMode: 'hybrid',
        stipendOrSalaryRange: 'NPR 8k-15k per month',
        requiredSkills: ['Python', 'Django', 'Git'],
        suitableCourses: ['BCA', 'BIT', 'BSc CSIT'],
        applicationDeadline: new Date('2027-12-31T23:59:59.999Z'),
        description: 'Build and maintain Django features with mentorship from the engineering team.',
        applicationLink: 'https://piinnovations.example/apply/python-django-intern',
        internalApplication: true,
        status: 'active',
        approvalStatus: 'approved',
    },
    {
        identity: { title: 'Frontend Developer Intern', companyName: 'Pi Innovations' },
        employerEmail: 'employer@edupath.local',
        title: 'Frontend Developer Intern',
        companyName: 'Pi Innovations',
        type: 'internship',
        location: 'Remote',
        workMode: 'remote',
        stipendOrSalaryRange: 'NPR 10k-18k per month',
        requiredSkills: ['JavaScript', 'React', 'Git'],
        suitableCourses: ['BCA', 'BIT', 'BSc CSIT'],
        applicationDeadline: new Date('2027-12-31T23:59:59.999Z'),
        description: 'Collaborate with designers and engineers to ship accessible React interfaces.',
        applicationLink: 'https://piinnovations.example/apply/frontend-intern',
        internalApplication: true,
        status: 'active',
        approvalStatus: 'approved',
    },
];

const onlineClasses = [
    {
        identity: { classTitle: 'Python for Beginners', instructorOrOrganization: 'EduPath Learning' },
        ownerEmail: 'instructor@edupath.local',
        classTitle: 'Python for Beginners',
        instructorOrOrganization: 'EduPath Learning',
        level: 'Beginner',
        mode: 'live',
        duration: '6 weeks',
        price: 0,
        subjects: ['Python', 'Programming Fundamentals'],
        certificateAvailability: true,
        description: 'A live, project-based introduction to Python for new programmers.',
        startDate: new Date('2027-06-01T00:00:00.000Z'),
        schedule: 'Saturdays and Sundays, 10:00 AM - 12:00 PM NPT',
        enrollmentLink: 'https://learn.edupath.example/python-beginners',
        approvalStatus: 'approved',
    },
    {
        identity: { classTitle: 'React Fundamentals', instructorOrOrganization: 'EduPath Learning' },
        ownerEmail: 'instructor@edupath.local',
        classTitle: 'React Fundamentals',
        instructorOrOrganization: 'EduPath Learning',
        level: 'Intermediate',
        mode: 'self_paced',
        duration: '4 weeks',
        price: 1500,
        subjects: ['React', 'JavaScript', 'Frontend Development'],
        certificateAvailability: true,
        description: 'Learn component-driven UI development, hooks, and application state in React.',
        startDate: new Date('2027-06-15T00:00:00.000Z'),
        schedule: 'Self-paced',
        enrollmentLink: 'https://learn.edupath.example/react-fundamentals',
        approvalStatus: 'approved',
    },
];

export { colleges, onlineClasses, opportunities, sampleUsers };
